# Generated by Django 4.0.8 on 2023-09-21 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('utm_tracker', '0001_initial'), ('utm_tracker', '0002_leadsource_created_at'), ('utm_tracker', '0003_increase_medium_chars'), ('utm_tracker', '0004_leadsource_gclid'), ('utm_tracker', '0005_auto_20210809_1259'), ('utm_tracker', '0006_leadsource_custom_tags'), ('utm_tracker', '0007_alter_leadsource_content'), ('utm_tracker', '0008_increase_charfield_lengths'), ('utm_tracker', '0009_alter_leadsource_timestamp')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(help_text='utm_medium: Identifies what type of link was used, such as cost per click or email.', max_length=100)),
                ('source', models.CharField(help_text='utm_source: Identifies which site sent the traffic, and is a required parameter.', max_length=100)),
                ('campaign', models.CharField(blank=True, help_text='utm_campaign: Identifies a specific product promotion or strategic campaign.', max_length=100)),
                ('term', models.CharField(blank=True, help_text='utm_term: Identifies search terms.', max_length=100)),
                ('content', models.CharField(blank=True, help_text='utm_content: Identifies what specifically was clicked to bring the user to the site, such as a banner ad or a text link.', max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, default=None, help_text='When the event occurred (if known).', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_sources', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the event was recorded.')),
                ('gclid', models.CharField(blank=True, help_text='Identifies a google click, is used for ad tracking in Google Analytics via Google Ads', max_length=255)),
                ('aclk', models.CharField(blank=True, help_text='Identifies a Microsoft Ad click (bing), is used for ad tracking.', max_length=255)),
                ('fbclid', models.CharField(blank=True, help_text='Identifies a Facebook Ad click, is used for ad tracking.', max_length=255)),
                ('msclkid', models.CharField(blank=True, help_text='Identifies a Microsoft Ad click (MS ad network), is used for ad tracking.', max_length=255)),
                ('twclid', models.CharField(blank=True, help_text='Identifies a Twitter Ad click, is used for ad tracking.', max_length=255)),
                ('custom_tags', models.JSONField(blank=True, default=dict, help_text='Dict of custom tag:value pairs as defined by the UTM_TRACKER_CUSTOM_TAGS setting.', null=True)),
            ],
            options={
                'get_latest_by': ('timestamp',),
            },
        ),
    ]
